### ISSUE TITLE
Maulik has shared with me a workspace that I don't want.

### ISSUE THREAD

**Issue by brettin** [PATRIC3/p3_web#468]
Maulik has shared a workspace with me. It shows up as a workspace in my account. I really don't want to see it, but I can't remove it. So Maulik can fill my workspace browser with stuff I don't want.

I couldn't find a way to deshare myself from his folder.

**Comment by nconrad** [comment]
Good point.  This would be a feature request from the service.  I created a ticket over there: PATRIC3/Workspace#59

**Comment by hyoo** [comment]
interesting user request... i know this is real..
